### ISSUE TITLE
Release of netstandard build?

### ISSUE THREAD

**Issue by richardjharding** [jmecsoftware/OpenCover2SonarConverter#1]
Hi do you have any plans to release a netstandard build? - I would like to run the tool on a linux build agent and the current release is a windows only binary?

I tried to build the source myself but it looks like it relies on a ```TestImpactApi``` package that I cant locate?

**Comment by jmecosta** [comment]
Yeah i can make those avaialble. The test impact api i have internally are
already .net standard. I will push those to nuget.org in the upcoming days

**Comment by jmecosta** [comment]
[ParseDiff.2.0.2.nupkg.zip](https://github.com/jmecsoftware/OpenCover2SonarConverter/files/3364538/ParseDiff.2.0.2.nupkg.zip)

**Comment by jmecosta** [comment]
@richardjharding there is a dependency to parsediff https://github.com/jkingry/ParseDiff/pull/5 so was not able to upload the nuget to nuget.org if u need to compile please add that nuget to your local cache. Ive release the tool as dotnet global tool so you can also just install it.
